name: Web-to-APK Builder

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'Website URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Replace Website URL
        run: |
          sed -i "s|REPLACE_ME_URL|${{ github.event.inputs.website_url }}|g" app/src/main/java/com/takbir/myapp/MainActivity.java

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Clean and Build APK
        # ./gradlew clean ব্যবহার করলে পুরানো ডাটা মুছে যাবে
        run: ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Takbir-App-Debug
          path: app/build/outputs/apk/debug/app-debug.apk
